### ISSUE TITLE
Mario in a vehicle is broken

### ISSUE THREAD

**Issue by 0x5066** [ckosmic/g64#52] opened 2022-06-26 04:09 UTC
With this new update, the camera now sits inside of Mario and the vehicle, rather than how it used to be, trying to get off the vehicle doesn't fully work.

Entering a vehicle causes a Lua error, exiting it also causes a Lua error as well.

```
Turning on prediction for new entity..
Shutdown 1 predictable entities and 0 client-created entities
Turning off prediction for old entity..

[G64] lua/entities/g64_mario.lua:957: attempt to index global 'ply' (a nil value)
  1. BuildEntityFilter - lua/entities/g64_mario.lua:957
   2. VehicleTick - lua/entities/g64_mario.lua:1082
    3. unknown - lua/entities/g64_mario.lua:1124

Turning on prediction for new entity..
Shutdown 1 predictable entities and 0 client-created entities

[G64] lua/entities/g64_mario.lua:957: attempt to index global 'ply' (a nil value)
  1. BuildEntityFilter - lua/entities/g64_mario.lua:957
   2. VehicleTick - lua/entities/g64_mario.lua:1095
    3. unknown - lua/entities/g64_mario.lua:1124
```

Mario is then also unable to move once you exit the vehicle, though this happens independent of if Mario was initialized or not.

**Comment by ckosmic** [comment] 2022-06-26 04:18
Good catch, for some reason it didn't error for me but it should have since I made a typo in the code.  I just pushed a fix, so it should work now.  Also, because of the new vehicle camera behavior, the camera may be in first person view in certain vehicle addons like SCars by default, but you can press Ctrl to go into third person.  Most vehicles should go into third person by default, just SCars so far seems to be weird with the camera.

**Comment by 0x5066** [comment] 2022-06-26 16:42
Ah, I see, I only use the HL2 vehicles and it threw me off for a bit as the camera would also usually follow the direction/rotation of the vehicle, didnt think to press Ctrl to switch to thirdperson mode

**Comment by 0x5066** [comment] 2022-06-26 16:48
Just tested the addon again and the vehicle stuff is working properly again
Thanks!

**Comment by 0x5066** [comment] 2022-06-26 16:52
Orrr not...
For some reason, if Mario is in a vehicle (in this case, a HL2 vehicle) and you delete him by pressing R, you yourself exit the vehicle with no weapon drawn and Mario is despawned, spawning him again however, he's unable to move whatsoever.

**Comment by ckosmic** [comment] 2022-06-27 04:37
I haven't been able to reproduce Mario not being able to move, but I wonder if it has anything to do with how I handle checking if the spawn menu is open to block inputs: https://github.com/ckosmic/g64/blob/master/lua/entities/g64_mario.lua#L981.  I'm gonna change it to not rely on hooks.
The no weapon bug will be fixed too.

**Closed** 2022-06-27 20:41 UTC
