### ISSUE TITLE
Camera issues with certain maps

### ISSUE THREAD

**Issue by PapaYosh** [ckosmic/g64#72] opened 2022-09-07 02:33 UTC
First off, goated mod, easily one of the best mods released this year.

The issue that I'm facing has to do the camera and how it's displayed in certain maps, specifically the Half-Life Resized Maps (https://steamcommunity.com/sharedfiles/filedetails/?id=971893221)

On a first time load (Opening a map for the first time, selecting the G64 entity), the mod works perfect! On changing between normal gmod mode and G64 mode in the same server, the camera gets locked in a pseudo-first-person view and flickers between that and third-person. Same thing happens if I reload the world and use the entity. The only current fix I can find is to restart the game.

For testing purposes I tried G64 on some bigger maps (gm_big city, gm_valley, gm_mountains, gm_lunarbase) to see if the issue was size related and none of those maps had any issues with it.

I tried sifting through the addons that I had activated to see if any of them were causing issues, and I'll probably check again just to be sure, but I couldn't find anything that was causing issues. (The collections I'm using; https://steamcommunity.com/sharedfiles/filedetails/?id=2746069840 https://steamcommunity.com/sharedfiles/filedetails/?id=2820582458)

Couldn't find any errors in the console while this was happening either (photo attached).

I recorded the issue so I could show what actually happens in game (Link to vid, was too large to include in github: https://www.youtube.com/watch?v=ySeo4ylOOUo) . I think it's something to do with how either the mod or map display where the player is. As seen near the end, jumping on the table shows the gmod playermodel teleporting back and forth from the g64 player and what I can only assume to be the shadow realm.

I haven't seen this bug in any other maps so far, I tried both the mounted version of the Half-life Source maps and the mounted version of the Half-Life 2 maps to see if this could be replicated in those maps and they both worked perfectly, so it's _MOST_ likely an issue with this set of maps in particular, but if it can happen on this map it can probably happen on others as well. If it's a map specific issue, I'll leave a comment on the steam page for the Half-Life Resized Maps notifying them of the issue as well.

Hoping this can get fixed, it would be so fun to play as Mario in Half-Life lmao.

![console](https://user-images.githubusercontent.com/112994887/188773038-cc310ff8-8cdb-43ac-be00-e92ff7203226.png)

**Comment by Luigifan2019** [comment] 2022-09-08 18:43
has the camera been going inside mario? its been doing that for me.

**Comment by ckosmic** [comment] 2022-09-09 04:41
Hey thanks for the genuinely good issue submission. I didn't experience this bug myself so the video and text details helped a lot. I found the cause for it and pushed a fix to the workshop. https://github.com/ckosmic/g64/commit/a1fe7b60be6b1e44ec815f4088ab7532f70b5243

**Closed by ckosmic** 2022-09-09 04:41 UTC
